# Dictionary of popular websites
websites = {
    "google": "https://www.google.com",
    "github": "https://github.com/VivekDhobale-VivekXploit",
    "youtube": "https://www.youtube.com",
    "linkedin": "https://www.linkedin.com",
    "facebook": "https://www.facebook.com",
    "instagram": "https://www.instagram.com",
    "twitter": "https://twitter.com",
    "whatsapp": "https://web.whatsapp.com",
    "reddit": "https://www.reddit.com",
    "pinterest": "https://www.pinterest.com",
    "snapchat": "https://www.snapchat.com",
    "tiktok": "https://www.tiktok.com",
    "quora": "https://www.quora.com",
    "medium": "https://medium.com",
    "netflix": "https://www.netflix.com",
    "prime video": "https://www.primevideo.com",
    "hotstar": "https://www.hotstar.com",
    "spotify": "https://open.spotify.com",
    "soundcloud": "https://soundcloud.com",
    "gmail": "https://mail.google.com",
    "yahoo mail": "https://mail.yahoo.com",
    "outlook": "https://outlook.live.com",
    "stackoverflow": "https://stackoverflow.com",
    "chatgpt": "https://chat.openai.com",
    "bing": "https://www.bing.com",
    "duckduckgo": "https://duckduckgo.com",
    "bbc": "https://www.bbc.com",
    "cnn": "https://edition.cnn.com",
    "times of india": "https://timesofindia.indiatimes.com",
    "hindustan times": "https://www.hindustantimes.com"
}